#!/usr/bin/env python3
import os
from pathlib import Path
import stat

# CONFIG
SODA_ROOT = Path(__file__).parent.parent.parent
HOOKS_DIR = SODA_ROOT / ".git/hooks"

# HOOK TEMPLATES (Shell Scripts)
# Fixed: Checks if script exists before running
PRE_COMMIT_HOOK = """#!/bin/sh
# SODA RULER: Pre-Commit Hook
# Validates Code Quality (Lint) and Basic SOP Compliance
# Bypass: git commit --no-verify

echo "👮 Ruler: Checking the Law... (Pre-Commit)"

# 1. Run Linter (If exists)
LINTER_SCRIPT=".agent/scripts/lint_runner.py"
if [ -f "$LINTER_SCRIPT" ]; then
    echo "   > Running Lint Runner..."
    python3 "$LINTER_SCRIPT" .
    LINT_EXIT=$?
    if [ $LINT_EXIT -ne 0 ]; then
        echo "❌ Ruler: Lint Failed. Committing garbage is illegal."
        exit 1
    fi
else
    echo "⚠️  Ruler: Linter script not found. Skipping validation (Risky)."
fi

echo "✅ Ruler: Proceeding."
exit 0
"""

PRE_PUSH_HOOK = """#!/bin/sh
# SODA RULER: Pre-Push Hook
# Validates System Integrity (Tests)
# Bypass: git push --no-verify

echo "👮 Ruler: Checking the Law... (Pre-Push)"

# 1. Run Tests (If exists)
TEST_SCRIPT=".agent/scripts/test_runner.py"
if [ -f "$TEST_SCRIPT" ]; then
    echo "   > Running Test Runner..."
    python3 "$TEST_SCRIPT"
    TEST_EXIT=$?
    if [ $TEST_EXIT -ne 0 ]; then
        echo "❌ Ruler: Tests Failed. You cannot push broken code."
        exit 1
    fi
else
    echo "⚠️  Ruler: Test runner not found. Skipping validation (Risky)."
fi

echo "✅ Ruler: System integrity confirmed."
exit 0
"""

def install_hooks():
    """Installs the git hooks."""
    if not HOOKS_DIR.exists():
        print(f"❌ .git/hooks directory not found at {HOOKS_DIR}")
        return

    # Install pre-commit
    pc_path = HOOKS_DIR / "pre-commit"
    pc_path.write_text(PRE_COMMIT_HOOK)
    pc_path.chmod(pc_path.stat().st_mode | stat.S_IEXEC)
    print(f"✅ Ruler: Installed pre-commit hook at {pc_path}")

    # Install pre-push
    pp_path = HOOKS_DIR / "pre-push"
    pp_path.write_text(PRE_PUSH_HOOK)
    pp_path.chmod(pp_path.stat().st_mode | stat.S_IEXEC)
    print(f"✅ Ruler: Installed pre-push hook at {pp_path}")

def compile_rules():
    """Compiles rule fragments into a Single Source of Truth (AGENTS.md)."""
    print("\n📜 Ruler: Compiling Law from Fragments...")
    
    fragments_dir = SODA_ROOT / ".agent/rules/fragments"
    if not fragments_dir.exists():
        print(f"⚠️  Fragments dir not found: {fragments_dir}")
        return

    # 1. Collect Fragments
    content = ["<!-- GENERATED BY RULER. DO NOT EDIT DIRECTLY. -->\n"]
    for fragment in sorted(fragments_dir.glob("*.md")):
        print(f"   + Linking {fragment.name}...")
        content.append(fragment.read_text() + "\n---")

    # 2. Write to AGENTS.md (The SODA Constitution)
    target = SODA_ROOT / ".agent/AGENTS.md"
    target.write_text("\n".join(content))
    print(f"✅ Ruler: Compiled {target}")
    
    # 3. Sync to Root .rules.md (For external tools)
    root_rules = SODA_ROOT / ".rules.md"
    root_rules.write_text("\n".join(content))
    print(f"✅ Ruler: Synced {root_rules}")

def main():
    print("👑 Ruler: SODA Governance Enforcer (The Compiler)")
    install_hooks()
    compile_rules()

if __name__ == "__main__":
    main()
